
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./roof-calc_backend_DB/src/BD/sql_roof-calc.sql:/docker-entrypoint-initdb.d/sql_roof-calc.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - zog_zog

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      VIRTUAL_HOST: phpmyadmin.local
      PMA_ARBITRARY: '1'
      PMA_HOSTS: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
    ports:
      - 3080:80
    restart: always
    depends_on:
      - db
    networks:
      - zog_zog

  backend:
    build: ./roof-calc_backend_DB
    depends_on:
      - db
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3001:3001"
    volumes:
      - ./roof-calc_backend_DB:/app
    restart: always
    networks:
      - zog_zog

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../../etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - '443:443'
    depends_on:
      - backend
      - frontend
    restart: always
    networks:
      - zog_zog

  frontend:
    build: ./roof_calc_frontend
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./roof_calc_frontend:/app
    depends_on:
      - backend
    networks:
      - zog_zog

networks:
  zog_zog:

volumes:
  db-data: