services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sql_roof-calc
      MYSQL_USER: kurwa
      MYSQL_PASSWORD: root
      MYSQL_SSL_MODE: DISABLED
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./roof-calc_backend_DB/src/BD/sql_roof-calc.sql:/docker-entrypoint-initdb.d/sql_roof-calc.sql
      - '../../etc/letsencrypt:/etc/letsencrypt'
    command: 
      --default-authentication-plugin=mysql_native_password
    networks:
      - zog_zog

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: '1'
      PMA_HOSTS: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 3080:3080
    restart: always
    depends_on:
      - db
    networks:
      - zog_zog

  backend:
    build: ./roof-calc_backend_DB
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: sql_roof-calc
    ports:
      - "3001:3001"
    links:
      - db
    volumes:
      - ./roof-calc_backend_DB:/app
      - '../../etc/letsencrypt:/etc/letsencrypt'
    restart: always
    networks:
      - zog_zog

  nginx:
    image: nginx:stable-alpine
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '../../etc/letsencrypt:/etc/letsencrypt'
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    restart: always
    networks:
      - zog_zog

  frontend:
    build: ./roof_calc_frontend
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./roof_calc_frontend:/app
    depends_on:
      - backend
    networks:
      - zog_zog

networks:
  zog_zog:

volumes:
  db-data: